version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports: ["8000:8000"]
    env_file: .env
    depends_on: [postgres, redis]
    volumes:
      - ./src:/app/src
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: dz
      POSTGRES_PASSWORD: dz
      POSTGRES_DB: dz_biometric
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file: .env
    depends_on: [redis, postgres]
    entrypoint: celery -A src.workers.celery_app worker -l info

volumes:
  pgdata: